name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - feature/**

env:
  LIBRARY: gil
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  posix:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: gcc-6
            cxxstd: "14,1z"
            os: ubuntu-latest
            container: ubuntu:18.04
            install: g++-6
          - toolset: gcc-7
            cxxstd: "14,17"
            install: g++-7
            os: ubuntu-latest
            container: ubuntu:20.04
          - toolset: gcc-8
            cxxstd: "14"
            os: ubuntu-latest
            container: ubuntu:20.04
            install: g++-8
          - toolset: gcc-9
            cxxstd: "14,17"
            os: ubuntu-24.04
            install: g++-9
          - toolset: gcc-10
            cxxstd: "14,17"
            os: ubuntu-24.04
            install: g++-10
          - toolset: gcc
            compiler: g++-11
            cxxstd: "14,17"
            os: ubuntu-24.04
            install: g++-11
          - toolset: gcc
            compiler: g++-12
            cxxstd: "14,17,20"
            os: ubuntu-24.04
            install: g++-12
          - toolset: gcc
            compiler: g++-13
            cxxstd: "14,17,20"
            os: ubuntu-24.04
            install: g++-13
          - toolset: gcc
            compiler: g++-14
            cxxstd: "14,17,20"
            os: ubuntu-24.04
            install: g++-14
          - toolset: gcc
            compiler: g++-15
            cxxstd: "14,17,20"
            os: ubuntu-latest
            container: ubuntu:25.04
            install: g++-15
          - toolset: clang
            compiler: clang++-3.9
            cxxstd: "14"
            os: ubuntu-latest
            container: ubuntu:18.04
            install: clang-3.9
          - toolset: clang
            compiler: clang++-4.0
            cxxstd: "14"
            os: ubuntu-latest
            container: ubuntu:18.04
            install: clang-4.0
          - toolset: clang
            compiler: clang++-5.0
            cxxstd: "14,1z"
            os: ubuntu-latest
            container: ubuntu:18.04
            install: clang-5.0
          - toolset: clang
            compiler: clang++-6.0
            cxxstd: "14,17"
            os: ubuntu-latest
            container: ubuntu:20.04
            install: clang-6.0
          - toolset: clang
            compiler: clang++-7
            cxxstd: "14,17"
            os: ubuntu-latest
            container: ubuntu:20.04
            install: clang-7
          - toolset: clang
            compiler: clang++-8
            cxxstd: "14,17"
            os: ubuntu-latest
            container: ubuntu:20.04
            install: clang-8
          - toolset: clang
            compiler: clang++-9
            cxxstd: "14,17"
            os: ubuntu-latest
            container: ubuntu:20.04
            install: clang-9
          - toolset: clang
            compiler: clang++-10
            cxxstd: "14,17"
            os: ubuntu-latest
            container: ubuntu:20.04
            install: clang-10
          - toolset: clang
            compiler: clang++-11
            cxxstd: "14,17,20"
            os: ubuntu-22.04
            install: clang-11
          - toolset: clang
            compiler: clang++-12
            cxxstd: "14,17,20"
            os: ubuntu-22.04
            install: clang-12
          - toolset: clang
            compiler: clang++-13
            cxxstd: "14,17,20"
            os: ubuntu-22.04
            install: clang-13
          - toolset: clang
            compiler: clang++-14
            cxxstd: "14,17,20"
            os: ubuntu-24.04
            install: clang-14
          - toolset: clang
            compiler: clang++-15
            cxxstd: "14,17,20"
            os: ubuntu-24.04
            install: clang-15
          - toolset: clang
            compiler: clang++-16
            cxxstd: "14,17,20"
            os: ubuntu-24.04
            install: clang-16
          - toolset: clang
            compiler: clang++-17
            cxxstd: "14,17,20"
            os: ubuntu-latest
            container: ubuntu:24.04
            install: clang-17
          - toolset: clang
            compiler: clang++-18
            cxxstd: "14,17,20,23"
            os: ubuntu-24.04
            install: clang-18
          - toolset: clang
            compiler: clang++-19
            cxxstd: "14,17,20,23"
            os: ubuntu-24.04
            install: clang-19
          - toolset: clang
            compiler: clang++-20
            cxxstd: "14,17,20,23"
            os: ubuntu-latest
            container: ubuntu:25.04
            install: clang-20
          - toolset: clang
            cxxstd: "14,17"
            os: macos-13

    runs-on: ${{matrix.os}}
    container:
      image: ${{matrix.container}}
      volumes:
        - /node20217:/node20217:rw,rshared
        - ${{ startsWith(matrix.container, 'ubuntu:1') && '/node20217:/__e/node20:ro,rshared' || ' ' }}

    steps:
      - name: Setup container environment
        if: matrix.container
        run: |
          apt-get -y update
          apt-get -y install sudo python3 git g++ curl
          if [[ "${{matrix.container}}" == "ubuntu:1"* ]]; then
            # Node 20 doesn't work with Ubuntu 16/18  glibc: https://github.com/actions/checkout/issues/1590
            curl -sL https://archives.boost.io/misc/node/node-v20.9.0-linux-x64-glibc-217.tar.xz | tar -xJ --strip-components 1 -C /node20217
          fi

      - uses: actions/checkout@v4

      - name: Install packages
        if: matrix.install
        run: sudo apt-get -y install ${{matrix.install}}

      - name: Setup Boost
        run: |
          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
          BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
          cd ..
          git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
          git submodule update --init tools/boostdep
          python3 tools/boostdep/depinst/depinst.py --git_args "--jobs 3" $LIBRARY
          ./bootstrap.sh
          ./b2 -d0 headers

      - name: Create user-config.jam
        if: matrix.compiler
        run: |
          echo "using ${{matrix.toolset}} : : ${{matrix.compiler}} ;" > ~/user-config.jam
          cat ~/user-config.jam

      - name: Run tests
        if: "!matrix.define"
        run: |
          cd ../boost-root
          ./b2 -j3 libs/$LIBRARY/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} variant=debug,release

      - name: Run tests
        if: matrix.define
        run: |
          cd ../boost-root
          ./b2 -j3 libs/$LIBRARY/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} define=${{matrix.define}} variant=debug,release

  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: gcc
            cxxstd: "14,17"
            addrmd: 64
            os: windows-2022
          - toolset: msvc-14.3
            cxxstd: "14,17"
            addrmd: 32,64
            os: windows-2022

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Boost
        shell: cmd
        run: |
          if "%GITHUB_BASE_REF%" == "" set GITHUB_BASE_REF=%GITHUB_REF%
          set BOOST_BRANCH=develop
          if "%GITHUB_BASE_REF%" == "master" set BOOST_BRANCH=master
          cd ..
          git clone -b %BOOST_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          xcopy /s /e /q %GITHUB_WORKSPACE% libs\%LIBRARY%\
          git submodule update --init tools/boostdep
          python tools/boostdep/depinst/depinst.py --git_args "--jobs 3" %LIBRARY%
          cmd /c bootstrap
          b2 -d0 headers

      - name: Run tests
        if: startsWith(matrix.toolset, 'msvc')
        shell: cmd
        run: |
          cd ../boost-root
          b2 -j3 --abbreviate-paths libs/%LIBRARY%/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} address-model=${{matrix.addrmd}} variant=debug,release
      - name: Run tests
        if: startsWith(matrix.toolset, 'gcc')
        shell: cmd
        run: |
          cd ../boost-root
          b2 -j3 --abbreviate-paths libs/%LIBRARY%/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} address-model=${{matrix.addrmd}} cxxflags=-mbig-obj variant=debug,release
